name: Build

on:
  push:
    branches: ["main"]


jobs:
  check-build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - run: apt-get -y update && apt-get install -y python3 python3-pip python2
      - run: python3 -m pip install meson ninja pwntools
      - run: meson -Dinstall_pip_modules=true -Dinstall_path=$PWD/cgc-pie builddir-pie
      - run: meson -Db_pie=false -Dforce_nopie=true -Dinstall_pip_modules=true -Dinstall_path=$PWD/cgc-nopie builddir-nopie
      - run: meson compile -C builddir-pie
      - run: meson compile -C builddir-nopie
      - run: meson install -C builddir-pie
      - run: meson install -C builddir-nopie
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "cgc-pie,cgc-nopie"
          body: "Release containing PIE and NO-PIE builds from Ubuntu 20.04"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: "main"
          tag: "main/${{ github.sha }}"
