name: Build

on: [push]

jobs:
  check-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y python3 python3-pip python2
      - run: python3 -m pip install meson ninja pwntools
      - run: meson -Dinstall_pip_modules=true -Dinstall_path=./cgc-pie builddir-pie
      - run: meson -Db_pie=false -Dforce_nopie=true -Dinstall_pip_modules=true -Dinstall_path=./cgc-nopie builddir-nopie
      - run: meson compile -C builddir-pie
      - run: meson compile -C builddir-nopie
      - run: meson install -C builddir-pie
      - run: meson install -C builddir-nopie
      - uses: thedoctor0/zip-release@main
        with:
          type: 'tar'
          filename: release.tar.gz
          directory: .
          path: cgc-pie cgc-nopie
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz"
          body: "Release containing PIE and NO-PIE builds from Ubuntu 20.04"
          token: ${{ secrets.GITHUB_TOKEN }}

