name: Build

on:
  push:
    branches: ["main"]


jobs:
  check-build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container: ubuntu:22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: apt-get -y update && apt-get install -y python3 python3-pip python2 gh
      - run: python3 -m pip install meson ninja pwntools
      - run: meson -Dinstall_pip_modules=true -Dinstall_path=$PWD/cgc-pie builddir-pie
      - run: meson -Db_pie=false -Dforce_nopie=true -Dinstall_pip_modules=true -Dinstall_path=$PWD/cgc-nopie builddir-nopie
      - run: meson compile -C builddir-pie
      - run: meson compile -C builddir-nopie
      - run: meson install -C builddir-pie
      - run: meson install -C builddir-nopie
      - run: tar -czvf cgc.tar.gz cgc-pie cgc-nopie
      - run: |
          gh release create "main/${{ github.sha }}" \
            --repo "${{ github.repository }}" --title "Main ${{ github.sha }}" cgc-pie cgc-nopie

